config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :costumes do
    resources :bookings, only: [:create]
  end
  get "dashboard", to: 'pages#dashboard'
  resources :bookings, only: %i[index edit destroy]
  patch "bookings/:id/accept", to: 'bookings#accept', as: 'accept_booking'
  patch "bookings/:id/reject", to: 'bookings#cancel', as: 'cancel_booking'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :costume
  validates :status, :start_date, :end_date, presence: true
  validates :status, inclusion: { in: ["pending", "accepted", "cancelled"] }
  validate :start_date_future?
  validate :end_date_after_start_date

  private


  private

  def end_date_after_start_date
    return if end_date.blank? || start_date.blank?

    if end_date < start_date
      errors.add(:end_date, "must be after the start date")
    end
  end

  def start_date_future?
    if start_date < Date.today
      errors.add(:start_date, "can't be in the past")
    end
  end
end

app/models/costume.rb
class Costume < ApplicationRecord
  has_many :bookings, dependent: :destroy
  belongs_to :user
  validates :name, presence: true
  validates :category, presence: true
  validates :size, presence: true
  has_one_attached :photo
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :costumes, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_one_attached :photo
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :phone_number, :photo])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = Booking.all
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.status = "pending"
    @costume = Costume.find(params[:costume_id])
    @booking.costume = @costume
    @booking.user = current_user
    if @booking.save
      redirect_to costume_path(@costume)
    else
      render 'costumes/show'
    end
  end

  def accept
    @booking = Booking.find(params[:id])
    @booking.status = "accepted"
    @booking.save
    redirect_to dashboard_path(current_user)
  end

  def cancel
    @booking = Booking.find(params[:id])
    @booking.status = "cancelled"
    @booking.save
    redirect_to dashboard_path(current_user)
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to dashboard_path(current_user)
  end

  private

  def booking_params
    params.require(:booking).permit(:status, :start_date, :end_date, :costume_id)
  end
end

app/controllers/costumes_controller.rb
class CostumesController < ApplicationController
  def index
    @costumes = Costume.all

    @markers = @costumes.geocoded.map do |costume|
      {
        lat: costume.latitude,
        lng: costume.longitude,
        info_window: render_to_string(partial: "info_window", locals: { costume: costume }),
        image_url: helpers.asset_url('marker.gif')
      }
    end
  end

  def new
    @costume = Costume.new
  end

  def show
    find_costume
    @booking = Booking.new
  end

  def create
    @costume = Costume.new(costume_params)
    @costume.user = current_user
    if @costume.save
      redirect_to costume_path(@costume)
    else
      render :new
    end
  end

  def edit
    find_costume
  end

  def update
    find_costume
    if @costume.update(costume_params)
      redirect_to costume_path(@costume)
    else
      render :new
    end
  end

  def destroy
    find_costume
    @costume.destroy
    redirect_to costumes_path
  end

  private

  def find_costume
    @costume = Costume.find(params[:id])
  end

  def costume_params
    params.require(:costume).permit(:name, :category, :size, :price_per_day, :available?, :photo, :address)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def dashboard
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/costumes/_form.html.erb
<div class="container">
  <%= simple_form_for(@costume) do |f| %>
      <%= f.input :name %>
      <%= f.input :category, placeholder: 'Fantasy, horror,...', class:''%>
      <%= f.input :size, placeholder: 'in cm' %>
      <%= f.input :price_per_day, placeholder: "Price in €" %>
      <%= f.input :available? %>
      <%= f.input :address %>
      <%= f.input :photo, as: :file %>
      <%= f.submit class:'stylised-button'%>
      <% if @costume.id == nil %>
        <%= link_to 'Cancel', costumes_path, class:'stylised-button' %>
      <% else %>
        <%= link_to 'Cancel', costume_path(@costume), class:'stylised-button' %>
      <% end %>
  <% end %>
</div>

app/views/costumes/_info_window.html.erb
<h4><%= costume.name %></h4>
<p><%= costume.address %></p>

app/views/costumes/edit.html.erb
<%= render 'form', costume: @costume %>

app/views/costumes/index.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="textwelcome" style="text-align: center">
      <p class="text2">Make your DREAMS come TRUE<br> We have <%= @costumes.count %> costumes just for you!</p>
        <h1 class="welcometext"><span> Check these out! </span></h1>
    </div>
      <div class="eachcard">
    <div class="cards">
      <% @costumes.each do |costume| %>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path costume.photo.key %>')">
            <div class="index-card">
              <%= link_to costume.name, costume_path(costume), class: 'ms-3 text index-buttons' %>
            </div>
        </div>
      <% end %>
      </div>
    </div>
    <div class="container pb-5">
      <div class=" row justify-content-center pt-3 pb-5">
        <div class=" col-12 " style=" border: solid 1px rgb(245, 53, 101); border-radius:4px; width: 60%; height: 380px;"
          data-controller="mapbox"
          data-mapbox-markers-value="<%= @markers.to_json %>"
          data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
        </div>
      </div>
    </div>
  </div>
</div>

app/views/costumes/new.html.erb
<div class="container pt-5">
  <div class="row justify-content-center">
    <h2 class="text-center" style="font-family: Mr Dafoe; text-align: center; padding-top: 10px; font-size: 50px">Rent your <strong>S'tume!</strong></h2>
      <%= render "form", costume: @costume %>
  </div>
</div>

app/views/costumes/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-8" style="margin-top: 120px">
      <div class="card-product">
        <img src=<%= cl_image_path @costume.photo.key %> />
        <div class="card-product-infos">
          <h2><%= @costume.name %></h2>
          <p class="card-product-category"><strong><%= @costume.category %></strong></p>
          <p class="card-product-size"><%= @costume.size %> cm</p>
          <p class="card-product-address"><%= @costume.address %></p>
          <p class="card-product-price"><%= @costume.price_per_day %> €</p>
          <%= link_to "Delete", costume_path(@costume), method: :delete, data: { confirm: "Are you sure you want to delete this Costume?"}, class: "stylised-button", style:"position: absolute; right: 15px; bottom: 15px;" %>
          <%= link_to "Edit 'Stume", edit_costume_path(@costume), class:"stylised-button", style:"position: absolute; right: 90px; bottom: 15px;" %>
          <p class="tick"><% if @costume.available? == true %>
              <%= "✅" %>
              <% else %>
              <%= "❌" %>
              <% end %>
          </p>
        </div>
      </div>
    </div>
    <div class="col-4" style="margin-top: 120px">
      <div class="container">
        <div class="card" style="box-shadow: 0.8px 0.8px 2px rgb(245, 53, 101);">
          <div class="card-body" style="height: 302px">
            <div class="form-container"  data-controller="flatpickr">
              <%= simple_form_for [ @costume, @booking ] do |f| %>
                <%= f.input :start_date, as: :string, required: false, input_html: {class: "datepicker"} %>
                <%= f.input :end_date, as: :string, required: false, input_html: {class: "datepicker"} %>
                <%= f.submit "Book stume", data: { confirm: "Your S'tume is booked!"},  class: "stylised-button", style: "position: absolute; right: 130px; bottom: 40px;" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Stumes4Rent</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'pages/navbar' %>
    <%= yield %>
    <%= render 'pages/footer' %>
  </body>
</html>

app/views/pages/_banner.html.erb
<div class="banner">
  <div class="container">
    <h1>Rent the best <strong>S'TUMES</strong> and prepare to stand out!</h1>
    <p>😝 Come and take a peek 😝</p>
    <div class="container d-flex justify-content-center">
     <%= link_to "Right here", costumes_path, class: "btn btn-danger banner-buttons" %>
    </div>
  </div>
</div>

app/views/pages/_footer.html.erb
<div class="footer justify-content-center">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
  </div>
</div>

app/views/pages/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to image_tag("clown.png"), root_path, class:"navbar-brand"%>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class= "thetwobuttons">
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto">
            <li class="nav-item d-flex">
              <%= link_to "All S'tumes", costumes_path, class: 'nav-link'%>
            </li>
      </div>
        <% if user_signed_in? %>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <li class="nav-item d-flex">
            <%= link_to "Add a S'tume", new_costume_path, class: 'nav-link' %>
          </li>
      </div>
    </div>
    <div class="nav-item dropdown">
        <% if current_user.photo.attached? %>
          <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <% else %>
          <%= image_tag 'profilepicture.jpeg', class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <% end %>
        <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
          <%= link_to "Log out", destroy_user_session_path, class: "nav-link", method: :delete, class: "nav-link dropdown-item" %>
          <%= link_to "Dashboard", dashboard_path, class: "nav-link dropdown-item"%>
        </div>
    <% else %>
      <div class="nav-item">
        <%= link_to "Login", new_user_session_path, class: "nav-link" %>
      </div>
    <% end %>
      </div>
  </ul>
  </div>
</div>

app/views/pages/dashboard.html.erb
<div class="container">
  <div class="main-body">
    <div class="row gutters-sm">
      <div class="col-md-4 mb-3">
        <div class="card">
          <div class="card-body">
            <div class="d-flex flex-column align-items-center text-center">
                      <% if current_user.photo.attached? %>
                        <%= cl_image_tag current_user.photo.key, class:'dashboard-avatar'%>
                      <% else %>
                        <%= image_tag 'profilepicture.jpeg', class:'dashboard-avatar'%>
                      <% end %>
              <div class="mt-3">
                <h4 class="welcometext"><%= current_user.first_name %></h4>
                <p class="text-secondary mb-1">Costume freak</p>
                <p class="text-muted font-size-sm">Somewhere</p>
                <%# <button class="btn btn-outline-primary">Contact</button> %>
                <%# need to display our form for edit profile here  %>
              </div>
            </div>
          </div>
        </div>
        <% if current_user.costumes.empty? %>
            <div class="card h-10 mt-3">
              <div class="card-body">
                <h6 class="d-flex align-items-center mb-3 text2">Your s'tumes</h6>
                <div class="d-flex flex-column align-items-center text-center">
                  <small>Nothing here... For now!</small>
                </div>
              </div>
            </div>
            <% else %>
            <div class="card mt-3">
              <div class="card-body">
                <h6 class="d-flex align-items-center mb-3 text2">Your s'tumes</h6>
                <% current_user.costumes.each do |costume| %>
                  <div class="card-category mt-3" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%=cl_image_path costume.photo.key%>')">
                    <div class="index-card">
                      <%= link_to costume.name, costume_path(costume), class: 'ms-3 text index-buttons' %>
                    </div>
                  </div>
                <% end %>
              </div>
            </div>
            <% end %>
      </div>
      <div class="col-md-8">
        <div class="card mb-3">
          <div class="card-body">
            <div class="row">
              <div class="col-sm-3">
                <h6 class="mb-0  text2">Full Name</h6>
              </div>
              <div class="col-sm-9 text-secondary">
                <%= "#{current_user.first_name} #{current_user.last_name}" %>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <h6 class="mb-0 text2">Email</h6>
              </div>
              <div class="col-sm-9 text-secondary">
                <%= current_user.email %>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <h6 class="mb-0 text2">Phone</h6>
              </div>
              <div class="col-sm-9 text-secondary">
                <%= current_user.phone_number %>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-12">
                <%= link_to "Make it shine", edit_user_registration_path(current_user), class: "stylised-button" %>
                <%# <a class="btn btn-info" target="__blank" href="">Make it shine!</a> %>
              </div>
            </div>
          </div>
        </div>
        <div class="row gutters-sm">
          <div class="col-sm-6 mb-3">
            <% if current_user.costumes.each {|costume| costume.bookings.empty?} %>
            <div class="card">
              <div class="card-body">
                <h6 class="d-flex align-items-center mb-3 text2">Your s'tumes' bookings</h6>
                <div class="d-flex flex-column align-items-center text-center">
                  <small>Nothing here... For now!</small>
                </div>
              </div>
            <% else %>
            <div class="card">
              <div class="card-body">
                <h6 class="d-flex align-items-center mb-3 text2">Your s'tumes got booked!</h6>
                <% current_user.costumes.each do |costume| %>
                  <% costume.bookings.each do |booking| %>
                    <div class="card mt-3">
                      <div class="card-body">
                        <h5 class="card-title welcometext" style="text-align: center; color: rgb(245, 53, 101); font-size: 40px"><%= booking.costume.name %></h5>
                        <p class="card-text"><%= "Booked by : #{booking.user.first_name}" %></p>
                        <p class="card-text"><%= "From : #{booking.start_date} | To : #{booking.end_date}" %></p>
                        <p>Status : <%= booking.status %></p>
                        <% if booking.status == "pending" %>
                          <%= link_to "accept",
                                                accept_booking_path(booking),
                                                method: :patch,
                                                class: "stylised-button",
                                                style: "text-decoration: none; color:black;"%>
                          <%= link_to "cancel",
                                                cancel_booking_path(booking),
                                                method: :patch,
                                                class: "stylised-button",
                                                style: "text-decoration: none; color:black"%>
                        <% else %>
                          <%= link_to "❌",
                                            booking_path(booking),
                                            method: :delete,
                                            data: { confirm: "Are you sure?" },
                                            style: "text-decoration: none; position: absolute; right: 15px; top: 10px"%>
                        <% end %>
                      </div>
                    </div>
                  <% end %>
                <% end %>
              </div>
            <% end %>
            </div>
          </div>
          <div class="col-sm-6 mb-3">
            <% if current_user.bookings.empty? %>
            <div class="card h-10">
              <div class="card-body">
                <h6 class="d-flex align-items-center mb-3 text2">Your Bookings</h6>
                <div class="d-flex flex-column align-items-center text-center">
                  <small>Nothing here... For now!</small>
                </div>
              </div>
            <% else %>
            <div class="card">
              <div class="card-body">
                <h6 class="d-flex align-items-center mb-3 text2">Your Bookings</h6>
                <% current_user.bookings.each do |booking| %>
                <div class="card mt-3">
                  <div class="card-body">
                    <h5 class="card-title welcometext" style="text-align: center"><%= link_to booking.costume.name, costume_path(booking.costume), style: 'text-decoration: none; color: rgb(245, 53, 101); font-size: 40px'%></h5>
                    <p class="card-text"><%= "From : #{booking.start_date} | To : #{booking.end_date}" %></p>
                    <%= link_to "❌",
                                    booking_path(booking),
                                    method: :delete,
                                    data: { confirm: "Are you sure?" },
                                    style: "text-decoration: none; position: absolute; right: 15px; top: 10px"%>
                    <p class="card-text">Status : <%= booking.status %></p>
                  </div>
                </div>
                <% end %>
              </div>
            <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<%= render "banner" %>